###########################################
# BASE IMAGE
###########################################

FROM openjdk:21-jdk AS builder

WORKDIR /opt/app

copy /usr/share/maven .mvn/
copy /usr/share/maven ./
copy /root/Docker-Zero-to-Hero/examples/golang-multi-stage-docker-build/java-hello-world-with-maven/pom.xml ./

run ./mvnw dependency:go-offline

copy /usr/share/maven/src ./src

RUN ./mvnw clean install


############################################
# HERE STARTS THE MAGIC OF MULTI STAGE BUILD
############################################

FROM openjdk:21-slim AS final

workdir /opt/app

EXPOSE 8080

# Copy the compiled binary from the build stage
COPY --from=builder /opt/app/target/*.jar  /opt/app/target/*.jar

# Set the entrypoint for the container to run the binary
ENTRYPOINT ["java","-jar", "/opt/app/target/*.jar"]
